version: '3'
services:
  service1:
    build:
      context: ./service1
    volumes:
      - ./logs:/logs
    depends_on:
      - service2
    networks:
      - mynetwork

  service2:
    build:
      context: ./service2
    volumes:
      - ./logs:/logs
    networks:
      - mynetwork

networks:
  mynetwork:
