version: '3'
services:
  service1:
    build:
      context: ./service1
    container_name: samundra-service1-container
    image: samundra-service1-image
    volumes:
      - ./logs:/logs
    depends_on:
      - service2
    networks:
      - mynetwork

  service2:
    build:
      context: ./service2
    container_name: samundra-service2-container
    image: samundra-service2-image
    volumes:
      - ./logs:/logs
    networks:
      - mynetwork

networks:
  mynetwork:
